name: tests

on:
  pull_request:
    branches:
      - v1
      - master
      - architecture

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.CI_SSH_KEY }}

      - name: set git email
        run: git config user.email ${{ secrets.CI_EMAIL }}

      - name: set git user
        run: git config user.name ${{ secrets.CI_USER }}

      - name: run all tests
        run: ./ci/tests.sh

